# Generated by Django 2.0.4 on 2018-07-14 20:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_default_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=markdownx.models.MarkdownxField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(max_length=1000),
        ),
    ]
