# Generated by Django 2.0.4 on 2018-06-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_default_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='position_applicants', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_line',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
