# Generated by Django 2.0.4 on 2018-07-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_default_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
