# Generated by Django 2.0.4 on 2018-07-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_default_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='any_applicants',
        ),
    ]
