# Generated by Django 2.0.4 on 2018-08-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_skillconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillconfirmation',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
