# Generated by Django 2.0.4 on 2018-05-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='filled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
